/**
 * reportGenerator
 * Simple text lab report generator that accepts experiment metadata and data
 * and produces a plain-text report suitable for student export.
 */

export function generateReport({ title, description, experimentType, results, statistics }: any) {
  const lines: string[] = [];
  lines.push(`Experiment Report - ${title}`);
  lines.push(`Type: ${experimentType}`);
  lines.push('');
  if (description) lines.push(`Description: ${description}`, '');

  if (statistics) {
    lines.push('Statistics:');
    Object.keys(statistics).forEach((k) => {
      const v = statistics[k];
      lines.push(`- ${k}: ${JSON.stringify(v)}`);
    });
    lines.push('');
  }

  if (results && results.length) {
    lines.push('Sample Data (first 20 rows):');
    const headers = Object.keys(results[0]);
    lines.push(headers.join('\t'));
    results.slice(0, 20).forEach((r: any) => {
      lines.push(headers.map((h) => String(r[h])).join('\t'));
    });
    lines.push('');
  }

  lines.push('Generated by SimuLab Engine');
  return lines.join('\n');
}
