import React, { useState } from 'react';
import Button from '@/components/ui/Button';
import { Download, FileText, Image } from 'lucide-react';
import { exportToCSV } from '@/lib/utils';
import html2canvas from 'html2canvas';

export interface ExportBtnProps {
  data: any[];
  chartRef?: React.RefObject<HTMLDivElement>;
  experimentName?: string;
}

const ExportBtn: React.FC<ExportBtnProps> = ({
  data,
  chartRef,
  experimentName = 'experiment',
}) => {
  const [isExporting, setIsExporting] = useState(false);

  const handleExportCSV = () => {
    if (data.length === 0) {
      alert('No data to export!');
      return;
    }

    exportToCSV(data, `${experimentName}_data_${Date.now()}.csv`);
  };

  const handleExportChart = async () => {
    if (!chartRef?.current) {
      alert('Chart not available for export!');
      return;
    }

    setIsExporting(true);

    try {
      const canvas = await html2canvas(chartRef.current, {
        backgroundColor: '#ffffff',
        scale: 2,
      });

      const link = document.createElement('a');
      link.download = `${experimentName}_chart_${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (error) {
      console.error('Failed to export chart:', error);
      alert('Failed to export chart');
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportReport = () => {
    if (data.length === 0) {
      alert('No data to generate report!');
      return;
    }

    // Calculate statistics
    const timeData = data.map((d) => d.time);
    const velocityData = data.map((d) => d.velocity || d.value);

    const avgVelocity = velocityData.reduce((a, b) => a + b, 0) / velocityData.length;
    const maxVelocity = Math.max(...velocityData);
    const totalTime = Math.max(...timeData);

    const report = `
EXPERIMENT REPORT: ${experimentName.toUpperCase()}
Generated: ${new Date().toLocaleString()}
========================================

SUMMARY:
- Total Duration: ${totalTime.toFixed(2)} seconds
- Data Points Collected: ${data.length}
- Average Velocity: ${avgVelocity.toFixed(2)} m/s
- Maximum Velocity: ${maxVelocity.toFixed(2)} m/s

DATA TABLE:
${Object.keys(data[0]).join('\t')}
${data.map((row) => Object.values(row).map((v: any) => 
  typeof v === 'number' ? v.toFixed(3) : v
).join('\t')).join('\n')}

========================================
Generated by SimuLab - Virtual Science Laboratory
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${experimentName}_report_${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-wrap gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handleExportCSV}
        leftIcon={<Download size={16} />}
        disabled={data.length === 0}
      >
        Export CSV
      </Button>

      {chartRef && (
        <Button
          variant="outline"
          size="sm"
          onClick={handleExportChart}
          leftIcon={<Image size={16} />}
          isLoading={isExporting}
          disabled={!chartRef.current}
        >
          Export Chart
        </Button>
      )}

      <Button
        variant="outline"
        size="sm"
        onClick={handleExportReport}
        leftIcon={<FileText size={16} />}
        disabled={data.length === 0}
      >
        Generate Report
      </Button>
    </div>
  );
};

export default ExportBtn;